In [2]:
import os
import quandl
import pandas as pd
API_KEY = os.environ.get('QUANDL_API_KEY')
fmac_df = quandl.get('FMAC/HPI', authtoken=API_KEY)
fmac_df.to_pickle('fmac_all_states.pickle')

In [5]:
fiddle_states = pd.read_html('https://simple.wikipedia.org/wiki/List_of_U.S._states')[0]
states_df = (fiddle_states['Flag, name and postal abbreviation [1]']
                    .rename(columns={'Flag, name and postal abbreviation [1]': 'State', 'Flag, name and postal abbreviation [1].1': 'Code'})
                    )
states_df["Code"].to_pickle('states.pickle')

In [34]:
fmac_df.columns

Index(['AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA', 'HI',
       'IA', 'ID', 'IL', 'IN', 'KS', 'KY', 'LA', 'MA', 'MD', 'ME', 'MI', 'MN',
       'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH', 'NJ', 'NM', 'NV', 'NY', 'OH',
       'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VA', 'VT', 'WA',
       'WI', 'WV', 'WY', 'United States not seasonaly adjusted',
       'United States seasonaly adjusted'],
      dtype='object')

,AK,AL,AR,AZ,CA,CO,CT,DC,DE,FL,...,TX,UT,VA,VT,WA,WI,WV,WY,United States not seasonaly adjusted,United States seasonaly adjusted
Date,,,,,,,,,,,,,,,,,,,,,
1975-01-31,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
1975-02-28,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
1975-03-31,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
1975-04-30,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
1975-05-31,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2017-08-31,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
2017-09-30,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
2017-10-31,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
2017-11-30,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
2017-12-31,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True